name: Deploy API
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chamando Webhook de Deploy
        run: |
          curl -X POST "https://entregahub.com.br/deploy-now?auth=${{ secrets.DEPLOY_PASSWORD }}&project=api"